[package]
name = "bamtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.40.2"
#threads_pool = "0.2.6"
rustc-hash = "1.1.0"
clap = "4.1.4"
ahash = "0.8.3"
